vich_uploader:
    db_driver: orm

    mappings:
        image_file:
            uri_prefix: '%app.upload.images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            upload_destination: '%kernel.project_dir%/public%app.upload.images%'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
